name: Check

on:
  push:
    branches: ["master"]
jobs:
  job-check:
    runs-on: ubuntu:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Maven compile
        run: mvn compile